name: Test Module Against Multiple TF Versions

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  test-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_version: ['1.3.9', '1.4.6', '1.5.7']

    defaults:
      run:
        working-directory: modules/test-module

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.tf_version }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="message=Hello from ${{ matrix.tf_version }}" -input=false -lock=false -no-color
